name       : kpkpass
version    : 21.08.3
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kpkpass-21.08.3.tar.xz : c5b1acc4a41747a8be381388101b401d7156abebd755c92176443cfb5019d650
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
