name       : kpkpass
version    : 21.04.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/kpkpass-21.04.0.tar.xz : b117e2b04f66e101662ef85a56e2636d78b4092e897f14ff0c27ce61874c2e68
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
