name       : kpkpass
version    : 18.08.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kpkpass-18.08.3.tar.xz : 690b710a1c397f3513ac9984a8127b0613a80101a794704063bc659d03475b9b
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
