name       : kpkpass
version    : 22.04.1
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kpkpass-22.04.1.tar.xz : 5e5cadca3951f7e3439713f295d549e0ab2f5e4a013c604fb9a703ea9e99411d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
