name       : kpkpass
version    : 19.08.1
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kpkpass-19.08.1.tar.xz : 893ee1f127c2d0c7135fe77c5c2895d04f95c9a6ed3b162c30856f4e99d4afb3
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
