name       : kpkpass
version    : 19.04.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/kpkpass-19.04.1.tar.xz : fb3554b04d00b326d5f5e14af9c0272c020092d3329808a6177fb0714f6a1cb7
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
