name       : kpkpass
version    : 21.08.1
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kpkpass-21.08.1.tar.xz : 7387ab4ef2fa48b839850f3ca1dc852b4551b9e881fc8f703cc3738548990d7d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
