name       : kpkpass
version    : 23.04.2
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kpkpass-23.04.2.tar.xz : a80fc873f4cacfac4bff692ad956523694568c5c2376ef1348768c7a615d5cd8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
