name       : kpkpass
version    : 18.08.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kpkpass-18.08.0.tar.xz : f4f31281a7d3335cb010f5ac6af2c5227f1b1e21fad2dd175633598bba67fef1
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
