name       : kpkpass
version    : 22.04.2
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kpkpass-22.04.2.tar.xz : dc128dde0166f1c16e54d639ebd88ed78c9467fbb44da4e01c7cac519641d845
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
