name       : kpkpass
version    : 18.12.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kpkpass-18.12.3.tar.xz : cd70809ab7a052e0ca2a18266ec5564bde16ac917988798290e3f01e428bd84f
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
