name       : kpkpass
version    : 18.12.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kpkpass-18.12.0.tar.xz : 86c9555b83d4c04903a3f225ba7a19e3f359da73839be0802b80703edf97351f
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
