name       : kpkpass
version    : 22.04.3
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kpkpass-22.04.3.tar.xz : 03eb257db51091bd3f2940db9d526a89155f8ec62b4b6f7a86e5b411bd515316
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
