name       : kpkpass
version    : 20.12.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kpkpass-20.12.0.tar.xz : a337c2e374d1b2e820b921911484425aabd4fe864fd5c8103931b7294d3617ec
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
