name       : kpkpass
version    : 18.12.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kpkpass-18.12.2.tar.xz : 0dd611334d2b48d2765b859a435e96b67928d8bb7ba3c6b2ae4c2be568e778d6
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
