name       : kpkpass
version    : 19.12.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kpkpass-19.12.0.tar.xz : 81032fd3807195109450141cd007dbd24a84fc789a83f68885c0a7dcbe2d66b4
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
