name       : kpkpass
version    : 19.04.2
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/kpkpass-19.04.2.tar.xz : 7d009a8441b5132460c1ad95812a4dded32f93e54eabccac236e7f2aeb20d828
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
