name       : kpkpass
version    : 19.08.3
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kpkpass-19.08.3.tar.xz : 6d70d3bcc949e83543ae7cf9d22280c270107bd9c9cb2882d6b37f6d036f5126
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
