name       : kpkpass
version    : 19.08.2
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kpkpass-19.08.2.tar.xz : daf4da30fd5c834915e6210bf64609adc116e5c6919365d000a400b6cd5f3e26
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
