name       : kpkpass
version    : 23.04.3
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kpkpass-23.04.3.tar.xz : 6986ba289ac03760c0ae8dddadabcbdf45835634a7b89b05cbea4bf7fd1873d0
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
