name       : kpkpass
version    : 21.12.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kpkpass-21.12.3.tar.xz : 678e79e450c5859d53c436ab991f4eadffd742dad129e4254953b98e2944c815
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
