name       : kpkpass
version    : 19.12.2
release    : 19
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kpkpass-19.12.2.tar.xz : 166b3a5b384bd606924e0c5e30878adc3dfbc1f0dc260a1f43df303d1c94b575
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
