name       : kpkpass
version    : 20.08.3
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kpkpass-20.08.3.tar.xz : 3ac6186bdd30cb535bf6cbcf43be7f9c6fbc8a3ba9d1bd3a501f8d584bef837f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
