name       : kpkpass
version    : 21.12.1
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kpkpass-21.12.1.tar.xz : 7c59c6ff3e00535988eea9675b793f67a78bfd30ea8d448f3f7dc8d4107b052a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
