name       : kpkpass
version    : 21.04.1
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kpkpass-21.04.1.tar.xz : 5368717031967d9134f1efe3ba72119b1574db5568a6818a1fd12014b9f58cb8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
