name       : kpkpass
version    : 23.04.1
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kpkpass-23.04.1.tar.xz : fb9cdc75a43fca6704e66e96c99cd080de797dcf07387da198a8af150dad0e53
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
