name       : kpkpass
version    : 21.04.3
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kpkpass-21.04.3.tar.xz : 4fe41557a06645b49de981c2cbb1f4189c2e0fe49b29d7c9020990b76716bff8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
