name       : kpkpass
version    : 20.08.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/kpkpass-20.08.0.tar.xz : 553b841cf3fdf4809251941997f7dee8e09360a5b7df386e3540c73d176ba055
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
