name       : kpkpass
version    : 20.08.2
release    : 27
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/kpkpass-20.08.2.tar.xz : ed699c75128ef299f06d699c80c69ac9529fa044db6f18a39d54a5e70d85108c
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
