name       : kpkpass
version    : 20.04.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kpkpass-20.04.0.tar.xz : 06f2183c6bafcba14f9842840b585828e5e4d4d40212567b03e0bbad90600654
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
