name       : kpkpass
version    : 20.04.1
release    : 22
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kpkpass-20.04.1.tar.xz : c7841a70df52bd5ba8dbf4e8358b9728b287c1513315135c7ca3ba76cec3cd0d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
