name       : kpkpass
version    : 22.08.3
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kpkpass-22.08.3.tar.xz : 64ab77fc62a1a3dde07827a6275b94e08b2956decf6cb183294c9b468e63f9e6
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
