name       : kpkpass
version    : 18.08.1
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kpkpass-18.08.1.tar.xz : 9326886a15d3539f0c44a9faf489d2f969d5a3fa2b773de125e496d17211a185
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
