name       : kpkpass
version    : 22.04.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kpkpass-22.04.0.tar.xz : 03036288aa35f93f77da3fad3a8a06021d6e85e1689de6584a7aa6fe7842673a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
