name       : kpkpass
version    : 20.04.2
release    : 23
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/kpkpass-20.04.2.tar.xz : 128d6ff4481d22373f15eccd227efcec6f3198487bf63204e02a2c26c9bdeefe
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
