name       : kpkpass
version    : 20.12.3
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kpkpass-20.12.3.tar.xz : e959224197521ed82ae98f7811fa03087c2397df9bbbc8ed7faf34e719558f51
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
