name       : kpkpass
version    : 20.08.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kpkpass-20.08.1.tar.xz : 76012e5bdd4cc434313a0f311acec8f7c798542008cd8efa71fcdf04fb77e55b
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
