name       : kpkpass
version    : 18.08.2
release    : 3
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kpkpass-18.08.2.tar.xz : aa2fdc4cd3a9186860a04cf75fae0b1f9d0b00d86be0bb0cfbc2cd3f65873b91
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
