name       : kpkpass
version    : 23.04.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kpkpass-23.04.0.tar.xz : f65010f35e72cf943282d8d28708c7b0859390dc3fb0b6d92277c473d27d4b38
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
