name       : kpkpass
version    : 20.12.2
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kpkpass-20.12.2.tar.xz : c3460c3673cb65df6cc9d89cec4c073b6dfd386af74be929a8ca557933c50cd4
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
