name       : kpkpass
version    : 21.12.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kpkpass-21.12.0.tar.xz : b69ba26ef69f72699995425323e55f7064623b3116d806dca65c2713a0e7770a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
