name       : kpkpass
version    : 21.04.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kpkpass-21.04.2.tar.xz : dc0794033abf028180d97b83f479f52aa921283db6e3dba47e73923f5f944610
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
