name       : kpkpass
version    : 21.08.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kpkpass-21.08.0.tar.xz : 500899c5ecd7244ae9cbbe6f30702709200cc2cea0479e48e2d5d1e9f2981315
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - karchive-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
