name       : kpkpass
version    : 19.12.3
release    : 20
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kpkpass-19.12.3.tar.xz : 45723989170e86c6739c8a377c54b3ba7456a8dc3ed6cf52eef884074c2df189
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Apple Wallet Pass reader
description: |
    Library to deal with Apple Wallet pass files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
